// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACcYUwFP8Qa0G6c5uI15BmZ_7oqTF2Xn0',
    appId: '1:91575713228:web:68b7e48ce98b46d222b169',
    messagingSenderId: '91575713228',
    projectId: 'cbc-learning-resources',
    authDomain: 'cbc-learning-resources.firebaseapp.com',
    storageBucket: 'cbc-learning-resources.appspot.com',
    measurementId: 'G-CE6Z22ZWQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdoBZkFAjdYqd0a991QbcZmKHhlGrauz0',
    appId: '1:91575713228:android:761195773b148d7a22b169',
    messagingSenderId: '91575713228',
    projectId: 'cbc-learning-resources',
    storageBucket: 'cbc-learning-resources.appspot.com',
  );
}
